# Generated by Django 4.1.4 on 2023-04-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('shape', models.CharField(max_length=250)),
                ('layers', models.PositiveIntegerField()),
            ],
        ),
    ]
