# Generated by Django 4.1.4 on 2023-05-02 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_alter_cakes_layers_alter_cakes_shape_reviews_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 5, 7)),
        ),
    ]
