# Generated by Django 4.1.4 on 2023-05-03 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_alter_cakes_layers_alter_cakes_shape'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 5, 8)),
        ),
    ]
