# Generated by Django 4.1.4 on 2023-05-04 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_rename_quantity_carts_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='matter',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 5, 5)),
        ),
    ]
